# Generated by Django 5.1.6 on 2025-02-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('IP', 'In Progress'), ('C', 'Completed'), ('X', 'Canceled')], default='R', max_length=2),
        ),
    ]
