# Generated by Django 5.1.6 on 2025-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_trip_id_alter_tripreview_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fare_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
