# Generated by Django 5.1.6 on 2025-02-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_trip_fare_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='total_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
